// old_ui_NOT_VALID/src/routes/licenses/+page.svelte
<script lang="ts">
  import { onMount } from 'svelte';
  import { toast } from 'svelte-french-toast';
  import {
    Key,
    Plus,
    Edit,
    Trash2,
    Search,
    Filter,
    Eye,
    Calendar,
    Download,
    RefreshCw
  } from 'lucide-svelte';

  import { licenseApi, tenantApi, templateApi } from '$lib/api';
  import Modal from '$components/Modal.svelte';
  import LicenseForm from '$components/LicenseForm.svelte';

  let licenses: any[] = [];
  let templates: any[] = [];
  let loading = true;
  let searchQuery = '';
  let selectedTenant = '';
  let currentPage = 1;
  let totalPages = 1;
  let pageSize = 10;

  // Modal states
  let showCreateModal = false;
  let showEditModal = false;
  let showDeleteModal = false;
  let showViewModal = false;
  let selectedLicense: any = null;

  // Tenants data for form dropdowns only
  let tenants: any[] = [];

  onMount(async () => {
    // Check if user is authenticated before loading data
    const token = sessionStorage.getItem('access_token');
    if (token) {
      await Promise.all([loadLicenses(), loadTenants(), loadTemplates()]);
    }
  });

  async function loadLicenses(page = 1) {
    try {
      loading = true;
      currentPage = page;

      const response = await licenseApi.getLicenses(page, pageSize, selectedTenant || undefined);
      licenses = response.items || [];
      totalPages = Math.ceil((response.total || 0) / pageSize);
      
      console.log('Loaded licenses:', licenses.length);
      if (licenses.length > 0) {
        console.log('Sample license with tenant_name:', {
          id: licenses[0].id,
          tenant_id: licenses[0].tenant_id,
          tenant_name: licenses[0].tenant_name
        });
      }
    } catch (error) {
      console.error('Error loading licenses:', error);
      toast.error('Failed to load licenses');
    } finally {
      loading = false;
    }
  }

  async function loadTenants() {
    try {
      // Only load for form dropdowns, not for table display
      const response = await tenantApi.getTenants(1, 200);
      tenants = response.items || [];
      console.log('Loaded tenants for forms:', tenants.length);
    } catch (error) {
      console.error('Error loading tenants:', error);
    }
  }

  async function loadTemplates() {
    try {
      const response = await templateApi.getTemplates(1, 200);
      templates = response.items || [];
    } catch (error) {
      console.error('Error loading templates:', error);
    }
  }

  function filteredLicenses() {
    if (!searchQuery) return licenses;
    return licenses.filter(license =>
      license.id.toString().includes(searchQuery) ||
      license.tenant_name.toLowerCase().includes(searchQuery.toLowerCase())
    );
  }

  function handleCreate() {
    selectedLicense = null;
    showCreateModal = true;
  }

  function handleEdit(license: any) {
    selectedLicense = license;
    showEditModal = true;
  }

  function handleDelete(license: any) {
    selectedLicense = license;
    showDeleteModal = true;
  }

  function handleView(license: any) {
    selectedLicense = license;
    showViewModal = true;
  }

  async function handleDownload(license: any) {
    try {
      console.log('Downloading license:', license.id);
      console.log('License key:', license.license_key);
      
      // Pass the license key to the API which will handle base64 encoding
      await licenseApi.downloadLicense(license.license_key);
      toast.success('License Download Complete\nThe license file has been downloaded successfully.');
    } catch (error) {
      console.error('Error downloading license:', error);
      toast.error('Failed to download license file');
    }
  }

  async function confirmDelete() {
    if (!selectedLicense) return;

    try {
      await licenseApi.deleteLicense(selectedLicense.id);
      toast.success('License revoked successfully');
      showDeleteModal = false;
      await loadLicenses(currentPage);
    } catch (error) {
      console.error('Error deleting license:', error);
    }
  }

  async function handleFormSuccess() {
    showCreateModal = false;
    showEditModal = false;
    // Add a small delay to ensure database transaction completes
    setTimeout(() => loadLicenses(currentPage), 500);
  }

  function handleTenantFilter() {
    currentPage = 1;
    loadLicenses(1);
  }
</script>

<svelte:head>
  <title>Licenses - Sigma Permit</title>
</svelte:head>

<div class="space-y-6">
  <!-- Header -->
  <div class="flex items-center justify-between">
    <div>
      <h1 class="text-3xl font-bold text-gray-900 dark:text-gray-50">Licenses</h1>
      <p class="text-gray-600 dark:text-gray-400 mt-2">Issue and manage license keys for your tenants</p>
    </div>
    <div class="flex items-center space-x-3">
      <button
        class="btn btn-primary p-2"
        on:click={() => loadLicenses(currentPage)}
        title="Refresh"
      >
        <RefreshCw size={18} />
      </button>
      <button
        class="btn btn-primary flex items-center space-x-2"
        on:click={handleCreate}
      >
        <Plus size={18} />
        <span>Create License</span>
      </button>
    </div>
  </div>

  <!-- Search and Filters -->
  <div class="card p-4">
    <div class="flex flex-col sm:flex-row gap-4">
      <div class="flex-1">
        <input
          type="text"
          placeholder="Search licenses..."
          class="form-input w-full"
          bind:value={searchQuery}
        />
      </div>
      <div class="flex items-center space-x-2">
        <select
          class="form-input"
          bind:value={selectedTenant}
          on:change={handleTenantFilter}
        >
          <option value="">All Tenants</option>
          {#each tenants as tenant}
            <option value={tenant.id}>{tenant.name}</option>
          {/each}
        </select>
      </div>
      <div class="text-sm text-gray-600 dark:text-gray-400">
        {filteredLicenses().length} of {licenses.length} licenses
      </div>
    </div>
  </div>

  <!-- Licenses Table -->
  <div class="card">
    <div class="table-container">
      {#if loading}
        <div class="flex items-center justify-center py-12">
          <div class="spinner mr-3"></div>
          <span class="text-gray-600 dark:text-gray-400">Loading licenses...</span>
        </div>
      {:else if filteredLicenses().length === 0}
        <div class="text-center py-12">
          <Key class="mx-auto text-gray-400 mb-4" size={48} />
          <h3 class="text-lg font-medium text-gray-900 dark:text-gray-50 mb-2">No licenses found</h3>
          <p class="text-gray-600 dark:text-gray-400 mb-4">
            {searchQuery || selectedTenant ? 'Try adjusting your filters.' : 'Get started by issuing your first license.'}
          </p>
          {#if !searchQuery && !selectedTenant}
            <button class="btn btn-primary flex items-center space-x-2 mx-auto" on:click={handleCreate}>
              <Plus size={18} />
              <span>Create License</span>
            </button>
          {/if}
        </div>
      {:else}
        <table class="table">
          <thead>
            <tr>
              <th>License ID</th>
              <th>Tenant</th>
              <th>Issued</th>
              <th>Validity Days</th>
              <th>Status</th>
              <th class="text-right">Actions</th>
            </tr>
          </thead>
          <tbody>
            {#each filteredLicenses() as license}
              <tr class="hover:bg-gray-50 dark:hover:bg-gray-800">
                <td class="font-mono text-sm font-medium text-gray-900 dark:text-gray-50">
                  {license.id.toString().substring(0, 8)}
                </td>
                <td class="text-gray-600 dark:text-gray-400">
                  {license.tenant_name}
                </td>
                <td class="text-gray-600 dark:text-gray-400">
                  <div class="flex items-center space-x-1">
                    <Calendar size={14} />
                    <span>{new Date(license.issued_at).toLocaleDateString()}</span>
                  </div>
                </td>
                <td class="text-gray-600 dark:text-gray-400">
                  {license.validity_days} days
                </td>
                <td>
                  <span class="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400">
                    Active
                  </span>
                </td>
                <td class="text-right">
                  <div class="flex items-center justify-end space-x-2">
                    <button
                      class="p-1 text-gray-400 hover:text-blue-500 rounded"
                      on:click={() => handleView(license)}
                      title="View license details"
                    >
                      <Eye size={16} />
                    </button>
                    <button
                      class="p-1 text-gray-400 hover:text-green-500 rounded"
                      on:click={() => handleDownload(license)}
                      title="Download license file"
                    >
                      <Download size={16} />
                    </button>
                    <button
                      class="p-1 text-gray-400 hover:text-blue-500 rounded"
                      on:click={() => handleEdit(license)}
                      title="Edit license"
                    >
                      <Edit size={16} />
                    </button>
                    <button
                      class="p-1 text-gray-400 hover:text-red-500 rounded"
                      on:click={() => handleDelete(license)}
                      title="Revoke license"
                    >
                      <Trash2 size={16} />
                    </button>
                  </div>
                </td>
              </tr>
            {/each}
          </tbody>
        </table>
      {/if}
    </div>

    <!-- Pagination -->
    <div class="flex items-center justify-between px-6 py-4 border-t border-gray-200 dark:border-gray-700">
      <div class="flex items-center space-x-4">
        <!-- Page Size Selector -->
        <div class="flex items-center space-x-2">
          <label for="pageSize" class="text-sm text-gray-600 dark:text-gray-400">Show:</label>
          <select
            id="pageSize"
            class="form-input w-20"
            bind:value={pageSize}
            on:change={() => { currentPage = 1; loadLicenses(1); }}
          >
            <option value={10}>10</option>
            <option value={20}>20</option>
            <option value={50}>50</option>
            <option value={100}>100</option>
            <option value={150}>150</option>
            <option value={200}>200</option>
          </select>
          <span class="text-sm text-gray-600 dark:text-gray-400">per page</span>
        </div>

        <!-- Results Info -->
        <div class="text-sm text-gray-600 dark:text-gray-400">
          Showing {Math.min((currentPage - 1) * pageSize + 1, licenses.length)} to {Math.min(currentPage * pageSize, licenses.length)} of {licenses.length} licenses
        </div>
      </div>

      <!-- Page Navigation -->
      {#if totalPages > 1}
        <div class="flex items-center space-x-2">
          <!-- First Page -->
          <button
            class="btn btn-secondary"
            disabled={currentPage === 1}
            on:click={() => loadLicenses(1)}
            title="First page"
          >
            ««
          </button>

          <!-- Previous Page -->
          <button
            class="btn btn-secondary"
            disabled={currentPage === 1}
            on:click={() => loadLicenses(currentPage - 1)}
            title="Previous page"
          >
            ‹
          </button>

          <!-- Page Numbers -->
          <div class="flex items-center space-x-1">
            {#each Array(Math.min(5, totalPages)) as _, i}
              {@const pageNum = Math.max(1, Math.min(totalPages - 4, currentPage - 2)) + i}
              {#if pageNum <= totalPages}
                <button
                  class="px-3 py-2 text-sm font-medium rounded-lg border transition-colors {pageNum === currentPage ? 'bg-blue-500 text-white border-blue-500 shadow-sm' : 'bg-white dark:bg-gray-800 text-gray-700 dark:text-gray-300 border-gray-300 dark:border-gray-600 hover:bg-gray-50 dark:hover:bg-gray-700'}"
                  on:click={() => loadLicenses(pageNum)}
                >
                  {pageNum}
                </button>
              {/if}
            {/each}
          </div>

          <!-- Next Page -->
          <button
            class="btn btn-secondary"
            disabled={currentPage === totalPages}
            on:click={() => loadLicenses(currentPage + 1)}
            title="Next page"
          >
            ›
          </button>

          <!-- Last Page -->
          <button
            class="btn btn-secondary"
            disabled={currentPage === totalPages}
            on:click={() => loadLicenses(totalPages)}
            title="Last page"
          >
            »»
          </button>
        </div>
      {/if}
    </div>
  </div>
</div>

<!-- Create License Modal -->
<Modal bind:open={showCreateModal} title="Create New License" size="lg" onClose={() => showCreateModal = false}>
  <LicenseForm
    tenants={tenants}
    templates={templates}
    on:success={handleFormSuccess}
    on:cancel={() => showCreateModal = false}
  />
</Modal>

<!-- Edit License Modal -->
<Modal bind:open={showEditModal} title="Edit License" size="lg" onClose={() => showEditModal = false}>
  <LicenseForm
    license={selectedLicense}
    tenants={tenants}
    templates={templates}
    on:success={handleFormSuccess}
    on:cancel={() => showEditModal = false}
  />
</Modal>

<!-- View License Modal -->
<Modal bind:open={showViewModal} title="License Details" size="lg" onClose={() => showViewModal = false}>
  <div class="space-y-6">
    <div class="grid grid-cols-2 gap-4">
      <div>
        <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">License ID</h3>
        <p class="text-lg font-mono font-medium text-gray-900 dark:text-gray-50">{selectedLicense?.id}</p>
      </div>
      <div>
        <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Tenant</h3>
        <p class="text-lg font-medium text-gray-900 dark:text-gray-50">{selectedLicense?.tenant_name || 'Unknown'}</p>
      </div>
      <div>
        <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Issued Date</h3>
        <p class="text-lg text-gray-900 dark:text-gray-50">{new Date(selectedLicense?.issued_at).toLocaleDateString()}</p>
      </div>
      <div>
        <h3 class="text-sm font-medium text-gray-500 dark:text-gray-400">Validity Days</h3>
        <p class="text-lg text-gray-900 dark:text-gray-50">{selectedLicense?.validity_days} days</p>
      </div>
    </div>

    {#if selectedLicense?.license_key}
      <div>
        <h3 class="text-lg font-medium text-gray-900 dark:text-gray-50 mb-3">License Key</h3>
        <div class="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
          <p class="text-sm font-mono text-gray-800 dark:text-gray-200 break-all">{selectedLicense.license_key}</p>
        </div>
        <p class="mt-2 text-sm text-gray-600 dark:text-gray-400">
          This key should be shared with the customer for offline license validation.
        </p>
      </div>
    {/if}

    {#if selectedLicense?.payload}
      <div>
        <h3 class="text-lg font-medium text-gray-900 dark:text-gray-50 mb-3">License Payload</h3>
        <div class="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
          <pre class="text-sm text-gray-800 dark:text-gray-200 overflow-x-auto"><code>{JSON.stringify(selectedLicense.payload, null, 2)}</code></pre>
        </div>
      </div>
    {/if}
  </div>

  <div slot="footer" class="flex justify-end">
    <button
      class="btn btn-secondary"
      on:click={() => showViewModal = false}
    >
      Close
    </button>
  </div>
</Modal>

<!-- Delete Confirmation Modal -->
<Modal bind:open={showDeleteModal} title="Revoke License" size="sm">
  <div class="space-y-4">
    <div class="flex items-start space-x-3">
      <div class="flex-shrink-0">
        <div class="w-10 h-10 bg-red-100 dark:bg-red-900/20 rounded-full flex items-center justify-center">
          <Trash2 class="text-red-600" size={20} />
        </div>
      </div>
      <div class="flex-1">
        <h3 class="text-lg font-medium text-gray-900 dark:text-gray-50">
          Revoke License
        </h3>
        <p class="text-gray-600 dark:text-gray-400 mt-1">
          Are you sure you want to revoke license <strong class="font-mono">{selectedLicense?.id}</strong>?
          This action cannot be undone.
        </p>
        <div class="mt-3 p-3 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
          <p class="text-sm text-yellow-800 dark:text-yellow-200">
            The license will become invalid and the tenant will lose access to the associated features.
          </p>
        </div>
      </div>
    </div>
  </div>

  <div slot="footer" class="flex justify-end space-x-3">
    <button
      class="btn btn-secondary"
      on:click={() => showDeleteModal = false}
    >
      Cancel
    </button>
    <button
      class="btn btn-danger"
      on:click={confirmDelete}
    >
      Revoke License
    </button>
  </div>
</Modal>

// react-frontend/src/app/licenses/page.tsx
'use client';

import { useState, useEffect } from 'react';
import ProtectedRoute from '@/components/ProtectedRoute';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Pagination } from '@/components/ui/pagination';
import {
  Key,
  Plus,
  Edit,
  Trash2,
  Search,
  CheckCircle,
  XCircle,
  Download,
  RefreshCw,
  Eye
} from 'lucide-react';
import { licenseApi } from '@/lib/api';
import { toast } from '@/lib/toast';
import LicenseForm from '@/components/forms/LicenseForm';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';

interface License {
  id: number;
  license_key: string;
  tenant_id: number;
  tenant_name: string;
  template_id?: number;
  linked_subscription?: string;
  issued_at?: string;
  validity_days?: number;
  payload: any;
  created_at: string;
}

export default function LicensesPage() {
  const [licenses, setLicenses] = useState<License[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState('');
  const [currentPage, setCurrentPage] = useState(1);
  const [totalPages, setTotalPages] = useState(1);
  const [totalItems, setTotalItems] = useState(0);
  const [pageSize, setPageSize] = useState(10);

  // Modal states
  const [showCreateModal, setShowCreateModal] = useState(false);
  const [showEditModal, setShowEditModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);
  const [showViewModal, setShowViewModal] = useState(false);
  const [selectedLicense, setSelectedLicense] = useState<any>(null);

  useEffect(() => {
    loadLicenses();
  }, []);

  const loadLicenses = async (page = 1, size = pageSize) => {
    try {
      setLoading(true);
      setCurrentPage(page);
      setPageSize(size);

      const response = await licenseApi.getLicenses(page, size);
      setLicenses(response.items || []);
      setTotalItems(response.total || 0);
      setTotalPages(Math.ceil((response.total || 0) / size));
    } catch (error) {
      console.error('Error loading licenses:', error);
      toast.error('Failed to load licenses');
    } finally {
      setLoading(false);
    }
  };

  const handlePageChange = (page: number) => {
    loadLicenses(page);
  };

  const handlePageSizeChange = (size: number) => {
    loadLicenses(1, size); // Reset to first page when changing page size
  };

  const filteredLicenses = licenses.filter(license =>
    license.id.toString().includes(searchQuery) ||
    license.tenant_id.toString().includes(searchQuery)
  );

  const handleRefresh = () => {
    loadLicenses(currentPage);
  };

  const handleCreate = () => {
    setSelectedLicense(null);
    setShowCreateModal(true);
  };

  const handleEdit = (license: any) => {
    setSelectedLicense(license);
    setShowEditModal(true);
  };

  const handleDelete = (license: any) => {
    setSelectedLicense(license);
    setShowDeleteModal(true);
  };

  const handleView = (license: any) => {
    setSelectedLicense(license);
    setShowViewModal(true);
  };

  const handleDownload = async (license: any) => {
    try {
      await licenseApi.downloadLicense(license.license_key);
    } catch (error) {
      console.error('Error downloading license:', error);
      toast.error('Failed to download license');
    }
  };

  const confirmDelete = async () => {
    if (!selectedLicense) return;

    try {
      await licenseApi.deleteLicense(selectedLicense.id.toString());
      toast.success(`License deleted successfully`);
      setShowDeleteModal(false);
      loadLicenses(currentPage);
    } catch (error) {
      console.error('Error deleting license:', error);
    }
  };

  const handleFormSuccess = () => {
    setShowCreateModal(false);
    setShowEditModal(false);
    setTimeout(() => loadLicenses(currentPage), 500);
  };

  const getLicenseType = (license: License): string => {
    // Try to get type from payload
    if (license.payload?.license_type) {
      return license.payload.license_type;
    }
    // Try to infer from template or payload content
    if (license.payload?.features?.includes('user_management')) {
      return 'Business';
    }
    if (license.payload?.features?.includes('basic')) {
      return 'Basic';
    }
    return 'Custom';
  };

  const getExpiryInfo = (license: License): { date: string; color: string; daysRemaining: number } => {
    if (!license.issued_at || !license.validity_days) {
      return {
        date: 'N/A',
        color: 'text-gray-500',
        daysRemaining: 0
      };
    }

    const issuedDate = new Date(license.issued_at);
    const expiryDate = new Date(issuedDate);
    expiryDate.setDate(expiryDate.getDate() + license.validity_days - 1);
    const now = new Date();
    const daysRemaining = Math.ceil((expiryDate.getTime() - now.getTime()) / (1000 * 60 * 60 * 24));

    let color = 'text-green-600';
    if (daysRemaining <= 10) {
      color = 'text-red-600';
    } else if (daysRemaining <= 20) {
      color = 'text-yellow-600';
    }

    return {
      date: expiryDate.toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' }),
      color,
      daysRemaining
    };
  };

  return (
    <ProtectedRoute>
      <div className="space-y-6">
        {/* Header */}
        <div className="flex items-center justify-between">
          <div>
            <h1 className="text-3xl font-bold text-gray-900 dark:text-gray-50">Licenses</h1>
            <p className="text-gray-600 dark:text-gray-400 mt-2">Manage license keys and their distribution</p>
          </div>
          <div className="flex items-center space-x-3">
            <Button
              variant="outline"
              size="sm"
              onClick={handleRefresh}
              title="Refresh"
            >
              <RefreshCw size={18} />
            </Button>
            <Button className="flex items-center space-x-2" onClick={handleCreate}>
              <Plus size={18} />
              <span>Issue License</span>
            </Button>
          </div>
        </div>

        {/* Search and Filters */}
        <Card className="p-4">
          <div className="flex items-center">
            <div className="relative flex-1">
              <Input
                type="text"
                placeholder="Search licenses..."
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="pr-10"
              />
              <div className="absolute inset-y-0 right-0 pr-3 flex items-center pointer-events-none">
                <Search size={18} className="text-gray-400" />
              </div>
            </div>
          </div>
        </Card>

        {/* Licenses Table */}
        <Card>
          <div className="overflow-x-auto">
            {loading ? (
              <div className="flex items-center justify-center py-12">
                <div className="animate-spin rounded-full h-8 w-8 border-b-2 border-blue-600 mr-3"></div>
                <span className="text-gray-600 dark:text-gray-400">Loading licenses...</span>
              </div>
            ) : filteredLicenses.length === 0 ? (
              <div className="text-center py-12">
                <Key className="mx-auto text-gray-400 dark:text-gray-500 mb-4" size={48} />
                <h3 className="text-lg font-medium text-gray-900 dark:text-gray-50 mb-2">No licenses found</h3>
                <p className="text-gray-600 dark:text-gray-400 mb-4">
                  {searchQuery ? 'Try adjusting your search terms.' : 'Get started by issuing your first license.'}
                </p>
                {!searchQuery && (
                  <Button className="flex items-center space-x-2 mx-auto">
                    <Plus size={18} />
                    <span>Issue License</span>
                  </Button>
                )}
              </div>
            ) : (
              <table className="w-full">
                <thead className="bg-gray-50 dark:bg-gray-800">
                  <tr>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      License ID
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Tenant
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Type
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Subscription
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Issued
                    </th>
                    <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Expires
                    </th>
                    <th className="px-6 py-3 text-right text-xs font-medium text-gray-500 dark:text-gray-400 uppercase tracking-wider">
                      Actions
                    </th>
                  </tr>
                </thead>
                <tbody className="bg-white dark:bg-gray-900 divide-y divide-gray-200 dark:divide-gray-700">
                  {filteredLicenses.map((license) => (
                    <tr key={license.id} className="hover:bg-gray-50 dark:hover:bg-gray-800">
                      <td className="px-6 py-4 whitespace-nowrap">
                        <code className="bg-gray-100 dark:bg-gray-800 px-2 py-1 rounded text-sm text-gray-800 dark:text-gray-200">
                          {license.id.toString().substring(0, 8)}
                        </code>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-gray-900 dark:text-gray-50">
                        {license.tenant_name || `Tenant ${license.tenant_id}`}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-gray-900 dark:text-gray-50">
                        {getLicenseType(license)}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        {license.linked_subscription ? (
                          <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-blue-100 text-blue-800 dark:bg-blue-900/20 dark:text-blue-400">
                            {license.linked_subscription.substring(0, 8)}...
                          </span>
                        ) : (
                          <span className="text-gray-400 dark:text-gray-500">None</span>
                        )}
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className="inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-300">
                          {license.issued_at ? new Date(license.issued_at).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' }) : 'N/A'}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap">
                        <span className={`inline-flex items-center px-2.5 py-0.5 rounded-full text-xs font-medium ${
                          getExpiryInfo(license).daysRemaining <= 10
                            ? 'bg-red-100 text-red-800 dark:bg-red-900/20 dark:text-red-400'
                            : getExpiryInfo(license).daysRemaining <= 20
                            ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900/20 dark:text-yellow-400'
                            : 'bg-green-100 text-green-800 dark:bg-green-900/20 dark:text-green-400'
                        }`}>
                          {getExpiryInfo(license).date}
                        </span>
                      </td>
                      <td className="px-6 py-4 whitespace-nowrap text-right">
                        <div className="flex items-center justify-end space-x-2">
                          <Button
                            variant="ghost"
                            size="sm"
                            className="text-gray-400 hover:text-purple-500"
                            title="View license details"
                            onClick={() => handleView(license)}
                          >
                            <Eye size={16} />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="text-gray-400 hover:text-green-500"
                            title="Download license"
                            onClick={() => handleDownload(license)}
                          >
                            <Download size={16} />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="text-gray-400 hover:text-blue-500"
                            title="Edit license"
                            onClick={() => handleEdit(license)}
                          >
                            <Edit size={16} />
                          </Button>
                          <Button
                            variant="ghost"
                            size="sm"
                            className="text-gray-400 hover:text-red-500"
                            title="Delete license"
                            onClick={() => handleDelete(license)}
                          >
                            <Trash2 size={16} />
                          </Button>
                        </div>
                      </td>
                    </tr>
                  ))}
                </tbody>
              </table>
            )}
          </div>
        </Card>

        {/* Pagination */}
        <Pagination
          currentPage={currentPage}
          totalPages={totalPages}
          pageSize={pageSize}
          totalItems={totalItems}
          onPageChange={handlePageChange}
          onPageSizeChange={handlePageSizeChange}
        />

        {/* Create License Modal */}
        <Dialog open={showCreateModal} onOpenChange={setShowCreateModal}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Issue New License</DialogTitle>
              <DialogDescription>
                Create a new license for a tenant with optional template validation.
              </DialogDescription>
            </DialogHeader>
            <LicenseForm
              onSuccess={handleFormSuccess}
              onCancel={() => setShowCreateModal(false)}
            />
          </DialogContent>
        </Dialog>

        {/* Edit License Modal */}
        <Dialog open={showEditModal} onOpenChange={setShowEditModal}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>Edit License</DialogTitle>
              <DialogDescription>
                Update license information and settings.
              </DialogDescription>
            </DialogHeader>
            <LicenseForm
              license={selectedLicense}
              onSuccess={handleFormSuccess}
              onCancel={() => setShowEditModal(false)}
            />
          </DialogContent>
        </Dialog>

        {/* View License Modal */}
        <Dialog open={showViewModal} onOpenChange={setShowViewModal}>
          <DialogContent className="max-w-2xl max-h-[90vh] overflow-y-auto">
            <DialogHeader>
              <DialogTitle>License Details</DialogTitle>
              <DialogDescription>
                Detailed information about the selected license.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-6">
              <div className="grid grid-cols-2 gap-4">
                <div>
                  <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400">License ID</h3>
                  <p className="text-lg font-mono font-medium text-gray-900 dark:text-gray-50">{selectedLicense?.id}</p>
                </div>
                <div>
                  <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400">Tenant</h3>
                  <p className="text-lg font-medium text-gray-900 dark:text-gray-50">{selectedLicense?.tenant_name || 'Unknown'}</p>
                </div>
                <div>
                  <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400">Linked Subscription</h3>
                  <p className="text-lg font-medium text-gray-900 dark:text-gray-50">
                    {selectedLicense?.linked_subscription ? (
                      <span className="font-mono">{selectedLicense.linked_subscription}</span>
                    ) : (
                      'None'
                    )}
                  </p>
                </div>
                <div>
                  <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400">Issued Date</h3>
                  <p className="text-lg text-gray-900 dark:text-gray-50">{selectedLicense?.issued_at ? new Date(selectedLicense.issued_at).toLocaleDateString('en-US', { day: 'numeric', month: 'short', year: 'numeric' }) : 'N/A'}</p>
                </div>
                <div>
                  <h3 className="text-sm font-medium text-gray-500 dark:text-gray-400">Validity Days</h3>
                  <p className="text-lg text-gray-900 dark:text-gray-50">{selectedLicense?.validity_days ? `${selectedLicense.validity_days} days` : 'N/A'}</p>
                </div>
              </div>

              {selectedLicense?.license_key && (
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-gray-50 mb-3">License Key</h3>
                  <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
                    <p className="text-sm font-mono text-gray-800 dark:text-gray-200 break-all">{selectedLicense.license_key}</p>
                  </div>
                  <p className="mt-2 text-sm text-gray-600 dark:text-gray-400">
                    This key should be shared with the customer for offline license validation.
                  </p>
                </div>
              )}

              {selectedLicense?.payload && (
                <div>
                  <h3 className="text-lg font-medium text-gray-900 dark:text-gray-50 mb-3">License Payload</h3>
                  <div className="bg-gray-50 dark:bg-gray-800 rounded-lg p-4">
                    <pre className="text-sm text-gray-800 dark:text-gray-200 overflow-x-auto"><code>{JSON.stringify(selectedLicense.payload, null, 2)}</code></pre>
                  </div>
                </div>
              )}
            </div>
            <div className="flex justify-end">
              <Button variant="outline" onClick={() => setShowViewModal(false)}>
                Close
              </Button>
            </div>
          </DialogContent>
        </Dialog>

        {/* Delete Confirmation Modal */}
        <Dialog open={showDeleteModal} onOpenChange={setShowDeleteModal}>
          <DialogContent>
            <DialogHeader>
              <DialogTitle>Delete License</DialogTitle>
              <DialogDescription>
                Are you sure you want to delete this license?
                This action cannot be undone.
              </DialogDescription>
            </DialogHeader>
            <div className="space-y-4">
              <div className="flex items-start space-x-3">
                <div className="flex-shrink-0">
                  <div className="w-10 h-10 bg-red-100 dark:bg-red-900/20 rounded-full flex items-center justify-center">
                    <Trash2 className="text-red-600 dark:text-red-400" size={20} />
                  </div>
                </div>
                <div className="flex-1">
                  <div className="mt-3 p-3 bg-yellow-50 dark:bg-yellow-900/20 border border-yellow-200 dark:border-yellow-800 rounded-lg">
                    <p className="text-sm text-yellow-800 dark:text-yellow-200">
                      The license will be permanently removed and cannot be recovered.
                    </p>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex justify-end space-x-3">
              <Button variant="outline" onClick={() => setShowDeleteModal(false)}>
                Cancel
              </Button>
              <Button variant="destructive" onClick={confirmDelete}>
                Delete License
              </Button>
            </div>
          </DialogContent>
        </Dialog>
      </div>
    </ProtectedRoute>
  );
}
